name: Unit Testing

on:
  pull_request:
  push:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    container:
      image: atk4/image:${{ matrix.php }}
    strategy:
      fail-fast: false
      matrix:
        php: ['latest']
        type: ['StaticAnalysis']
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure PHP
        run: |
          rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
          php --version

      - name: Install PHP dependencies
        run: |
          mv vendor/phpstan/phpstane phpstane
          composer update
          mv phpstane vendor/phpstan/phpstane
          rm -R vendor/phpstan/phpstan/* && touch vendor/phpstan/phpstan/bootstrap.php

      - name: Run Static Analysis
        run: |
          php vendor/phpstan/phpstane/bin/phpstan analyse --ansi --debug
