name: Unit Testing

on:
  pull_request:
    branches: '**'
  push:
    branches: '**'

jobs:
  build:
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest]
        php-versions: ['7.4']
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, intl
          ini-values: post_max_size=256M, log_errors=1, memory_limit=1G
          tools: composer
    
      - name: Configure PHP
        run: |
          php --version

      - name: Install PHP dependencies
        run: |
          composer update

      - name: Run Static Analysis
        run: |
          cd vendor/atk4/ui && php ../../phpstan/phpstan/phpstan analyse --ansi
